- project:
    name: openstack/panko
    check:
      jobs:
        - panko-tox-py27-mongodb
        - panko-tox-py27-mysql
        - panko-tox-py27-postgresql
        - panko-tox-py35-mongodb
        - panko-tox-py35-mysql
        - panko-tox-py35-postgresql
        - telemetry-dsvm-integration-panko
        # TripleO jobs that deploy Telemetry.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario00(1|2)-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario001-multinode-oooq:
            voting: false
        - tripleo-ci-centos-7-scenario001-multinode-oooq-container:
            voting: false
        - tripleo-ci-centos-7-scenario002-multinode-oooq:
            voting: false
        - tripleo-ci-centos-7-scenario002-multinode-oooq-container:
            voting: false
    gate:
      jobs:
        - panko-tox-py27-mongodb
        - panko-tox-py27-mysql
        - panko-tox-py27-postgresql
        - panko-tox-py35-mongodb
        - panko-tox-py35-mysql
        - panko-tox-py35-postgresql
        - telemetry-dsvm-integration-panko

- job:
    name: panko-tox-py27-mongodb
    parent: legacy-base
    run: playbooks/legacy/panko-tox-py27-mongodb/run.yaml
    post-run: playbooks/legacy/panko-tox-py27-mongodb/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: panko-tox-py27-mysql
    parent: legacy-base
    run: playbooks/legacy/panko-tox-py27-mysql/run.yaml
    post-run: playbooks/legacy/panko-tox-py27-mysql/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: panko-tox-py27-postgresql
    parent: legacy-base
    run: playbooks/legacy/panko-tox-py27-postgresql/run.yaml
    post-run: playbooks/legacy/panko-tox-py27-postgresql/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: panko-tox-py35-mongodb
    parent: legacy-base
    run: playbooks/legacy/panko-tox-py35-mongodb/run.yaml
    post-run: playbooks/legacy/panko-tox-py35-mongodb/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: panko-tox-py35-mysql
    parent: legacy-base
    run: playbooks/legacy/panko-tox-py35-mysql/run.yaml
    post-run: playbooks/legacy/panko-tox-py35-mysql/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: panko-tox-py35-postgresql
    parent: legacy-base
    run: playbooks/legacy/panko-tox-py35-postgresql/run.yaml
    post-run: playbooks/legacy/panko-tox-py35-postgresql/post.yaml
    timeout: 2400
    required-projects:
      - openstack/requirements

- job:
    name: telemetry-dsvm-integration-panko
    parent: legacy-dsvm-base
    run: playbooks/legacy/telemetry-dsvm-integration-panko/run.yaml
    post-run: playbooks/legacy/telemetry-dsvm-integration-panko/post.yaml
    timeout: 7800
    required-projects:
      - openstack-infra/devstack-gate
      - openstack/aodh
      - openstack/ceilometer
      - openstack/panko
      # following are required when DEVSTACK_GATE_HEAT, which this
      # job turns on
      - openstack/dib-utils
      - openstack/diskimage-builder
